version: "3.4"
services:
  cloudmapper:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_SECURITY_TOKEN
      - AWS_DEFAULT_REGION=eu-west-1
      - ACCOUNT
    ports:
      - "8000:8000"
    logging:
      driver: journald
